// vuemf-app/src/components/WordInput.vue
<script setup lang="ts">
import { ref } from 'vue'

const emit = defineEmits<{
  (e: 'add', word: string): void
}>()

const input = ref('')

const handleAdd = () => {
  if (input.value.trim()) {
    emit('add', input.value.trim())
    input.value = ''
  }
}
</script>

<template>
  <div class="flex mb-4">
    <input
      class="flex-1 border border-gray-300 rounded-l px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-600"
      type="text"
      placeholder="Enter a word..."
      v-model="input"
      @keydown.enter="handleAdd"
    />

    <button
      class="bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded-r font-semibold transition-colors"
      @click="handleAdd"
    >
      Add
    </button>
  </div>
</template>

// reactmf-app/src/components/WordInput.tsx
import React, { useState } from 'react';

type WordInputProps = {
  onAdd: (word: string) => void;
};

const WordInput: React.FC<WordInputProps> = ({ onAdd }) => {
  const [input, setInput] = useState('');

  const handleAdd = () => {
    if (input.trim()) {
      onAdd(input.trim());
      setInput('');
    }
  };

  return (
    <div className="flex mb-4">
      <input
        className="flex-1 border border-gray-300 rounded-l px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-400"
        type="text"
        placeholder="Enter a word..."
        value={input}
        onChange={e => setInput(e.target.value)}
        onKeyDown={e => e.key === 'Enter' && handleAdd()}
      />
      <button
        className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-r font-semibold transition-colors"
        onClick={handleAdd}
      >
        Add
      </button>
    </div>
  );
};

export default WordInput;
