// reactmf-app/src/components/WordCounter.tsx
import React from 'react';

type WordCounterProps = {
  count: number;
  source: string;
};

const WordCounter: React.FC<WordCounterProps> = ({ count, source }) => {
  return (
    <div className="mt-4 p-3 bg-green-50 border border-green-200 rounded-lg">
      <p className="text-sm text-green-800">
        <span className="font-semibold">{source}</span> has{' '}
        <span className="font-bold text-green-600">{count}</span> word{count !== 1 ? 's' : ''}
      </p>
    </div>
  );
};

export default WordCounter;

// vuemf-app/src/components/WordCounter.vue
<script setup lang="ts">
defineProps<{
  count: number
  source: string
}>()
</script>

<template>
  <div class="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
    <p class="text-sm text-blue-800">
      <span class="font-semibold">{{ source }}</span> has
      <span class="font-bold text-blue-600">{{ count }}</span> word{{ count !== 1 ? 's' : '' }}
    </p>
  </div>
</template>
